### ISSUE TITLE
Cocoapods!

### ISSUE THREAD

**Issue by bennyguitar** [jmascia/KLCPopup#1]
You should add this to [Cocoapods](http://cocoapods.org) so developers can easily add this library to their projects without having to pull down this repo and drag files over. This is a really cool library, and it'd be awesome to have a pod for it.

**Comment by jmascia** [comment]
Thanks benny, I'll work on it.

**Comment by myusuf3** [comment]
@jmascia do it, takes two seconds. :)

**Comment by jmascia** [comment]
Sorry sorry, I was a little busy. Thank you to @nicopuri for taking care of this. I tested and it works fine for me.

I'll submit to the Specs Repo, but this should work for now.

**Comment by jmascia** [comment]
It's in the Specs Repo now :)

**Comment by myusuf3** [comment]
:100:

**Comment by MaximKeegan** [comment]
Please update pod!

**Comment by michalshatz** [comment]
Whatsup? Is there a pod?
