### ISSUE TITLE
Errors when i press button in my view

### ISSUE THREAD

**Issue by smiless** [jmascia/KLCPopup#13]
Hello guys,

i have always one of these errors (randomly) when i press the button in my view  : 

With KLCPopup I have always one of these errors (randomly) when i press the button of my view contained in the KLCPopup:

 NSInvalidArgumentException', reason: '-[NSISLinearExpression sendPlus:](most of times) bad_access_exc code=1
Here's my code to call the KLCPopup in « FindViewController » 

AddFeelingViewController *adf = [self.storyboard instantiateViewControllerWithIdentifier:@"AddFeelingView"];
adf.userTo = [_userFetch objectAtIndex:indexPath.row];
adf.controller = self;
adf.view.frame = CGRectMake(0.0, 0.0, 300.0, 250.0);

KLCPopup *popup = [KLCPopup popupWithContentView:[adf view] showType:KLCPopupShowTypeBounceIn dismissType:KLCPopupDismissTypeBounceOut maskType:KLCPopupMaskTypeDimmed dismissOnBackgroundTouch:YES dismissOnContentTouch:NO];

[popup show];

And here the code called in my « AddFeelingViewController »  when i press the button :
- (void)viewDidLoad {
  
  [super viewDidLoad];
  score = 0;
  if([_controller isKindOfClass:[FindViewController class]]){
  
  ```
  _controller = (FindViewController*)_controller;
  ```
  
  }else{
      _controller = (HomeViewController*)_controller;
  
  }
- (IBAction)sendPlus:(id)sender {
  
    score = 1;

}

Everything is well linked in the storyboard and it only crashes if the buttons are linked.

Have you an idea ?

**Comment by gastonmz** [comment]
I have the same problem!

**Comment by smiless** [comment]
I resolved this issue like this : the controller/view put in the KLCPopup container must be a strong property in the class where the KLCPopup is created/called.
