### ISSUE TITLE
Dismiss popup using a button

### ISSUE THREAD

**Issue by lmrtn** [jmascia/KLCPopup#38]
Hello,

I've been using KLCPopup in my project, and I've been trying to dismiss a popup on button click.

Context : 
I have a nib with my popup , inside there are 2 buttons (yes, no).
I load my nib into my klcpopup and instantiate it to show on screen

Problem : 
When I click on one of the buttons, If I put anything in the IBAction connected to the button in nib, it will crash without telling me one thing in debugger, just gives me a EXC_BAD_ACCESS on AppDelegate class.

code snippets : 
my func to show the alert

```
func showAlertWithButtons(message: String?, title: String?) {
        var nibView = NSBundle.mainBundle().loadNibNamed("buttonAlertView", owner: self, options: nil)[0] as? UIView
        alertTitle.text = title!
        alertMessage.text = message!
        var mainWindow = UIApplication.sharedApplication().keyWindow
        nibView?.frame = CGRectMake(nibView!.frame.origin.x, nibView!.frame.origin.y, mainWindow!.frame.size.width, nibView!.frame.size.height)
        alertPopup = KLCPopup(contentView: nibView, showType: KLCPopupShowType.SlideInFromRight, dismissType: KLCPopupDismissType.GrowOut,
            maskType: KLCPopupMaskType.Dimmed, dismissOnBackgroundTouch: true, dismissOnContentTouch: false)

        alertPopup!.show()
    }
```

my IBAction

```
    @IBAction func didClickOnYes(sender : AnyObject)
    {}
```

my nib
![alt text](https://i.gyazo.com/6bc6fc952c54e7e552855eb58abe7750.png)

I tried setuping a nsnotification in my IBAction but it crashes.

Is there a way to dismiss my popup from an IBAction, if so what am I doing wrong ?

**Comment by Tibb** [comment]
Same for me: as soon as I add an UIButton and connect it to an IBAction, if I try to clic the button, it crashes my app with the EXC_BAD_ACCESS, no log, no exception raised on breakpoints... Help plz :)

**Comment by Tibb** [comment]
Found a solution: 
if your nib is linked to a ViewController, this controller is automatically released once the code of your method is executed. So your action cannot be triggered (more details in my [stackoverflow post](http://stackoverflow.com/a/32438937/2042510)).
Move your nib declaration to a class variable, this should do the trick ;)

**Comment by lmrtn** [comment]
Nice one thanks! will do that. Tried to simplify my code too much I guess haha!

**Comment by Tibb** [comment]
Pas de souci, j'ai fait exactement la même erreur! bonne continuation ;)

**Comment by lmrtn** [comment]
yep à toi aussi!
