### ISSUE TITLE
How to use didFinishDismissingCompletion block?

### ISSUE THREAD

**Issue by hemangshah** [jmascia/KLCPopup#8]
How to use

```
@property (nonatomic, copy) void (^didFinishDismissingCompletion)(); 
```

block to notify when popup get dismissed?

Any example would be appreciated.

**Comment by vamsiac** [comment]
here you go
    popUp.didFinishDismissingCompletion = ^(void) {
      //do your stuff here
    };

**Comment by hemangshah** [comment]
@vamsiac , wow! thank you so much :+1:
